server:
  port: 8091
  context-path: /big-crab-service
spring:
  jersey:
#    type: filter
#    application-path: /api
#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      ddl-auto: create
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bigcrab?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: bigcrab
    password: bigcrab
mybatis:
  typeAliasesPackage: com.victor.wang.bigCrab.model
  mapperLocations: classpath:mapper/*.xml